# sudo: required

language: generic

services:
  - docker

os: linux

dist: xenial

before_install:
  - docker build -t tngusdl527/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tngusdl527/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket: "elasticbeanstalk-ap-northeast-2-493277859606"
  bucket_path: "docker-react-app"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY