sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t tngusdl527/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tngusdl527/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"